name: pytorch_env
channels:
  - pytorch
  - nvidia/label/cuda-12.4.0 # 对于查找 NVIDIA CUDA 组件至关重要
  - conda-forge
  - defaults
dependencies:
  # Python 和核心包
  - python=3.10
  - pip
  - transformers
  - peft
  - accelerate
  - evaluate
  
  # 使用 pytorch-cuda 元包来拉取 PyTorch、torchvision、torchaudio，
  # 以及 CUDA 12.4 兼容的 cudatoolkit
  - pytorch-cuda=12.4 # 这将确保 PyTorch、torchvision、torchaudio 启用 CUDA 12.4
  - pytorch=2.6.0     # 指定 PyTorch 版本，让 pytorch-cuda 处理 CUDA 构建
  - torchvision=0.21.0
  - torchaudio=2.6.0
  
  # 其他 Conda 可以提供的必要库
  - numpy
  - pandas
  - scipy
  - tqdm