name: pytorch_env
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:

  - pytorch_geometric
  - accelerate=1.7.0
  - datasets=2.14.4
  - evaluate=0.4.3
  - faiss-cpu=1.9.0
  - fastapi=0.115.12
  - nltk=3.9.1
  - numpy=1.26.4
  - pandas=2.2.3
  - peft=0.15.2
  - pillow=11.2.1
  - pip=25.1.1
  - python=3.10.17
  - safetensors=0.5.3
  - tokenizers=0.21.1
  - tqdm=4.67.1
  - transformers=4.52.3
  - pytorch
  