name: pytorch_env
channels:
  - pytorch # PyTorch 官方 channel，用于获取 CUDA 支持的 PyTorch
  - nvidia/label/cuda-12.4.0 # 明确指定 CUDA 12.4 版本
  - conda-forge # 提供了许多科学计算和机器学习的包
  - defaults # conda 默认 channel
dependencies:
  # Python 和核心包
  - python=3.10
  - pip
  - transformers
  - peft
  - accelerate
  - evaluate
  - pytorch=2.6.0=cuda12.4_py310* # 指定 PyTorch 版本并强制 CUDA 12.4
  - torchvision=0.21.0=cuda12.4_py310* # 指定 torchvision 版本并强制 CUDA 12.4
  - torchaudio=2.6.0=cuda12.4_py310* # 指定 torchaudio 版本并强制 CUDA 12.4
  
  # 注意：torch_geometric 及其相关库通常建议通过 pip 安装预编译的 wheel 包，
  # 以确保与特定 PyTorch 和 CUDA 版本的兼容性。
  # 因此，这些将在 pip 部分处理。
pip:
  - torch_geometric
  - pyg_lib
  - torch_scatter
  - torch_sparse
  - torch_cluster
  - torch_spline_conv
  # 注意：pip install -f 后面的链接是数据源，conda 在处理 pip 部分时会使用它们