name: pytorch_env
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - accelerate=1.7.0
  - aiofiles=24.1.0
  - aiohttp=3.11.18
  - altair=5.5.0
  - anyio=4.9.0
  - arrow=1.3.0
  - attrs=25.3.0
  - bert_score=0.3.9
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - cffi=1.17.1
  - click=8.2.1
  - contourpy=1.3.2
  - cookiecutter=2.6.0
  - cycler=0.12.1
  - datasets=2.14.4
  - dill=0.3.7
  - evaluate=0.4.3
  - faiss-cpu=1.9.0
  - fastapi=0.115.12
  - filelock=3.18.0
  - fonttools=4.58.1
  - fsspec=2025.5.1
  - gmpy2=2.2.1
  - gradio=3.24.1
  - h11=0.16.0
  - huggingface_hub=0.31.4
  - idna=3.10
  - importlib-metadata=8.7.0
  - jinja2=3.1.6
  - joblib=1.5.1
  - jsonschema=4.24.0
  - kiwisolver=1.4.7
  - lerc=4.0.0
  - markdown-it-py=2.2.0
  - markupsafe=3.0.2
  - matplotlib-base=3.10.3
  - mdit-py-plugins=0.3.3
  - mpmath=1.3.0
  - multidict=6.4.4
  - multiprocess=0.70.15
  - munkres=1.1.4
  - networkx=3.4.2
  - nltk=3.9.1
  - numpy=1.26.4
  - openh264=2.6.0
  - optree=0.15.0
  - orc=2.1.2
  - packaging=25.0
  - pandas=2.2.3
  - peft=0.15.2
  - pillow=11.2.1
  - pip=25.1.1
  - pluggy=1.6.0
  - psutil=7.0.0
  - pyarrow=20.0.0
  - pybind11=2.13.6
  - pydantic=2.11.4
  - pydub=0.25.1
  - pygments=2.19.1
  - pyparsing=3.2.3
  - pytest=8.3.5
  - python=3.10.17
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.1.0
  - python-slugify=8.0.4
  - pytz=2025.2
  - pyyaml=6.0.2
  - regex=2024.11.6
  - requests=2.32.3
  - rich=14.0.0
  - safetensors=0.5.3
  - scipy=1.15.2
  - setuptools=80.8.0
  - six=1.17.0
  - sniffio=1.3.1
  - starlette=0.46.2
  - sympy=1.14.0
  - tk=8.6.13
  - tokenizers=0.21.1
  - tqdm=4.67.1
  - transformers=4.52.3
  - typing-extensions=4.13.2
  - typing_extensions=4.13.2
  - tzdata=2025b
  - urllib3=2.4.0
  - uvicorn=0.34.3
  - watchfiles=1.0.5
  - websockets=15.0.1
  - wheel=0.45.1
  - xxhash=0.8.3
  - yaml=0.2.5
  - zipp=3.21.0
  - zstd=1.5.7
  - cudatoolkit=11.8.0  # 添加CUDA支持
  - cudnn=8.9.2.26  # 添加cuDNN支持
  - pip:
      - torch==2.6.0+cu118 --extra-index-url https://download.pytorch.org/whl/cu118
      - torchvision==0.21.0+cu118 --extra-index-url https://download.pytorch.org/whl/cu118
      - torchaudio==2.6.0 --extra-index-url https://download.pytorch.org/whl/cu118
      - nvidia-cublas-cu11=11.10.3.66
      - nvidia-cuda-nvrtc-cu11=11.7.99
      - nvidia-cuda-runtime-cu11=11.7.99
      - nvidia-cudnn-cu11=8.5.0.96
      - fastapi-cli==0.0.7
      - gradio-client==1.10.2
      # 保留原始pip包
      - bert_score==0.3.9
      - ffmpy==0.3.0
      - email_validator==2.2.0
      - pydantic-core==2.33.2
      - rich-toolkit==0.11.3